name: kerani_sawit
description: Kerani Sawit - Sawit Lamandau Raya
publish_to: "none"
version: 1.15.0+71

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^10.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/headers/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/launcher_icon.png"
